apiVersion: v1
kind: Service
metadata:
    name: fin-receiver-service
spec:
    selector:
        app: fin-receiver
    ports:
        - name: web
          protocol: TCP
          port: 5555
          targetPort: 5555
          nodePort: 5555
    type: NodePort
