apiVersion: v1
kind: Service
metadata:
    name: nats-service
spec:
    selector:
        app: nats
    ports:
        - name: client
          protocol: TCP
          port: 4222
          targetPort: 4222
          nodePort: 4222
        - name: monitor
          protocol: TCP
          port: 6222
          targetPort: 6222
          nodePort: 6222
    type: NodePort
